const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const crypto=require('node:crypto');const root=path.join(__dirname,'..');
function app(){const context=vm.createContext({document:{addEventListener(){}},navigator:{userAgent:''},window:{}});for(const f of ['js/google-maps.js','js/now.js','js/app.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),context);return context;}
test('photo rendering distinguishes representative photographs without cluttering cards',()=>{const ctx=app();const html=ctx.mediaHTML({name:'未確認咖啡廳',image:'images/korea/c-cafe.jpg',imageAlt:'咖啡廳室內示意，非本次店家',imageType:'illustrative',imageNote:'實際店家尚未確認'});assert.match(html,/alt="咖啡廳室內示意，非本次店家"/);assert.match(html,/示意圖/);assert.doesNotMatch(html,/onerror=|圖片來源|授權/);const actual=ctx.mediaHTML({name:'景福宮',image:'images/korea/b-palace.jpg',imageAlt:'景福宮實景',imageType:'actual'});assert.doesNotMatch(actual,/photo-badge/);});
test('all 25 itinerary cards have JPEG signature and hash verified local photo assets and matching source metadata',()=>{const data=JSON.parse(fs.readFileSync(path.join(root,'data/itinerary.json'),'utf8'));const source=JSON.parse(fs.readFileSync(path.join(root,'data/photo-sources.json'),'utf8'));const cards=data.days.flatMap(d=>d.items.filter(i=>i.type==='spot'));assert.equal(cards.length,25);const keys=new Map(source.photos.map(p=>[p.key,p]));assert.equal(keys.size,source.photos.length);for(const card of cards){assert.match(card.image,/^images\/korea\/[abc]-[a-z0-9-]+\.jpg$/);assert.ok(card.imageAlt);const photo=keys.get(card.photoKey);assert.ok(photo,card.name);assert.equal(photo.image,card.image);assert.equal(photo.imageType,card.imageType);assert.ok(['actual','surroundings','illustrative'].includes(card.imageType));const bytes=fs.readFileSync(path.join(root,card.image));assert.equal(bytes.readUInt16BE(0),0xffd8);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),photo.sha256);for(const field of ['sourceUrl','originalUrl','author','license','licenseUrl'])assert.ok(photo[field],field);for(const field of ['sourceUrl','originalUrl','licenseUrl']){const u=new URL(photo[field]);if(photo.legacyHttpSource&&u.protocol==='http:'){assert.equal(u.hostname,'ap73.yncmedia.kr');assert.equal(u.port,'');assert(u.pathname==='/page/page3'||u.pathname.startsWith('/img_up/shop_pds/ap73/contents/'));}else assert.equal(u.protocol,'https:');assert.equal(u.username,'');assert.equal(u.password,'');}if(card.imageType!=='actual'){assert.match(card.imageAlt,/示意|周邊/);assert.ok(card.imageNote);}}});

test('image failure retains the itinerary card and safe text fallback',()=>{const ctx=app();let replaced;ctx.document.createElement=()=>({});const image={matches:s=>s==='img.media-img',getAttribute:()=>'<unsafe>',replaceWith:node=>{replaced=node;}};ctx.handlePhotoError({target:image});assert.equal(replaced.className,'media-ph');assert.equal(replaced.textContent,'圖片暫時無法載入');});
test('credits links reject scripts, relative URLs, HTTP and embedded credentials',()=>{const status={textContent:''};const ctx=vm.createContext({URL,document:{getElementById:()=>status},fetch:async()=>({ok:true,json:async()=>({photos:[]})})});vm.runInContext(fs.readFileSync(path.join(root,'js/photo-credits.js'),'utf8'),ctx);for(const url of ['javascript:alert(1)','http://example.com','https://user:pass@example.com','/relative'])assert.equal(ctx.safePhotoUrl(url),null);assert.equal(ctx.safePhotoUrl('https://commons.wikimedia.org/wiki/File:Photo.jpg'),'https://commons.wikimedia.org/wiki/File:Photo.jpg');});
test('photo credits inherit the same maple theme as the itinerary',()=>{const credits=fs.readFileSync(path.join(root,'photo-credits.html'),'utf8');assert.match(credits,/css\/maple-theme\.css/);assert(credits.indexOf('css/style.css')<credits.indexOf('css/maple-theme.css'));});
test('photo licensing has a single footer entry and a local source-driven standalone page',()=>{const index=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(index,/href="photo-credits.html"/);const credits=fs.readFileSync(path.join(root,'photo-credits.html'),'utf8');assert.match(credits,/圖片來源與授權/);assert.match(credits,/js\/photo-credits.js/);const js=fs.readFileSync(path.join(root,'js/photo-credits.js'),'utf8');assert.match(js,/data\/photo-sources.json/);assert.doesNotMatch(js,/innerHTML\s*=\s*.*photo/);});
